---
language: python
python: "2.7"

env:
  - distro: debian9
    version: latest
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

script:
  # Check if the bootstrap works
  - sudo bash bootstrap.sh

notifications:
  email:
    on_success: change
    on_failure: always
