---
- hosts: all
  any_errors_fatal: true
  roles:
    - common

#- name: Include users playbook
#  import_playbook: hardening.yml

- name: apply common configuration to raspberry pi nodes
  hosts: all
  remote_user: root
  vars:
    sshd_config:
      # https://dev.gentoo.org/~swift/docs/security_benchmarks/openssh.html
      Compression: "yes"
      GSSAPIAuthentication: "no"
      PermitRootLogin: "no"
      PasswordAuthentication: "no"
      IgnoreRhosts: "yes"
      RhostsRSAAuthentication: "no"
      HostbasedAuthentication: "no"
      PermitEmptyPasswords: "no"
      UseDNS: "no"
      UsePam: "no"
      ServerKeyBits: 2048
      Protocol: 2
      UsePrivilegeSeparation: "yes"
      X11Forwarding: "no"
      StrictModes: "yes"
      # AllowGroup: ssh
      # If not needed, disable TCP forwarding
      AllowTcpForwarding: "no"
      PubkeyAuthentication: "yes"

    raspberry_pi_boot_config_options:
        # dont load the audio kernel module
      - regexp: "^#?dtparam=audio"
        line: "dtparam=audio=off"
        # minimize the gpu mem
      - regexp: "^#?gpu_mem"
        line: "gpu_mem=16"
        # disable onboard BT
      - regexp: "^#?dtoverlay=pi3-disable-bt-overlay"
        line: "dtoverlay=pi3-disable-bt-overlay"
        # Enable 1200ma USB current on newer model Pis.
      - regexp: "^#?max_usb_current"
        line: "max_usb_current=1"

    # dev-sec.os-hardening
    ufw_manage_defaults: false
    os_auditd_enabled: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      # net.ipv4.ip_forward: 1
      vm.swappiness: 5
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 2048

    sudoers_sudoers:
      defaults:
        - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      user_aliases:
        - name: TESTING
          members: vagrant, travis
      privileges:
        - name: root
          entry: "ALL=(ALL:ALL) ALL"
        - name: "TESTING"
          entry: "ALL=(ALL:ALL) ALL"
        - name: "%sudo"
          entry: "ALL=NOPASSWD:ALL"
  roles:
    - { role: oefenweb.timezone }   # set timezone to UTC
    - { role: oefenweb.locales }    # set locale to en_US.UTF-8 UTF-8
    - { role: oefenweb.ntp }
    - { role: oefenweb.sudoers }
    - { role: reallyenglish.sshd }
    # - { role: oefenweb.swapfile, swapfile_size: 4GB, swapfile_swappiness: 10 }
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
      unattended_automatic_reboot: true
      # unattended_mail_only_on_error: true
      # unattended_mail: 'federico.castagnini+raspberrypi@gmail.com'
    - role: oefenweb.fail2ban
      fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 5
        findtime: 1800
    - role: singleplatform-eng.users
    - role: geerlingguy.raspberry-pi
    - role: dev-sec.os-hardening
  tasks:
    ##############################
    # Install prezto
    - name: Install zprezto for federico
      git: repo=https://github.com/sorin-ionescu/prezto.git
           dest=/home/federico/.zprezto
           recursive=yes
    - name: Fix permissions after zprezto install
      command: chown -R federico:federico /home/federico/.zprezto
    - name: Linking zprezto rc files
      copy: src=/home/federico/{{ item.src }} dest=/home/federico/{{ item.dest }} owner=federico group=federico force=no
      with_items:
        - { src: '.zprezto/runcoms/zlogin',    dest: '.zlogin' }
        - { src: '.zprezto/runcoms/zpreztorc', dest: '.zpreztorc' }
        - { src: '.zprezto/runcoms/zprofile',  dest: '.zprofile' }
        - { src: '.zprezto/runcoms/zshenv',    dest: '.zshenv' }
        - { src: '.zprezto/runcoms/zshrc',     dest: '.zshrc' }
    ##############################

    - cron: name="duckdns update sample" minute="*/15" user="federico"
            job="echo url=\"https://www.duckdns.org/update?domains=$(/bin/hostname).duckdns.org&token=exampletoken&ip=\" | curl -k -o /tmp/duck.log -K - >/dev/null 2>&1"
            cron_file=duckdns-update.sample
            state=present
            disabled=yes

    - name: Mount tmpfs paths
      mount:
        path={{ item.path }}
        src=tmpfs
        fstype=tmpfs
        opts=nodev,nosuid,size={{ item.size }}
        state=present
      with_items:
        - { path: '/tmp',     size: '20M' }
        - { path: '/var/tmp', size: '20M' }
