---
- name: apply common configuration to raspberry pi nodes
  hosts: localhost
  remote_user: root
  vars:
    sshd_skip_defaults: true
    sshd:
      Compression: true
      GSSAPIAuthentication: no
      PermitRootLogin: no
      # role: mivok0.users
    users:
      - username: federico
        name: Federico Castagnini
        groups: ['sudo']
        shell: /usr/bin/zsh
        uid: 2001
        ssh_key:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIWzy21UpPuFHiX0ENDB0K7SEFvOQW00REvlITr6MnZEI1izGpfhPh4Bfns/dx8IBf5pQZnJsqR1WdHCg9feqSb9gpyLl1CPnT1mXQJYefelSwgjQA5r8JEwPBLQldQeVYbWmeJbnzU7iJQsA8qQW9/D5ETTMl4fiJ4edrtFTJblHhq3kfJBACvfBEPE78hFSe/GgTe9mvQRMhhwXqhofUZ//oN6wLtXDH4IoLVOPpnMhPHVCL9kaThq8DbNLDkl5ZNIzT2pCKmtavVzJ3XeOnSJUuGKFvLqpqBanRHvt1Glfy3VEzOkCz9GUMF3u+/v+UUtOrESocfSOFy2QWYAbZ fede@arroz-con-leche"
  roles:
    - { role: tersmitten.timezone }   # set timezone to UTC
    - { role: tersmitten.locales }    # set locale to en_US.UTF-8 UTF-8
    - { role: tersmitten.ntp }
    # - { role: tersmitten.swapfile, swapfile_size: 4GB, swapfile_swappiness: 10 }
    - { role: jnv.unattended-upgrades }
    - { role: mattwillsher.sshd }
    - role: tersmitten.fail2ban
      fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 5
        findtime: 1800
    - role: mivok0.users
    - role: mivok0.sudo
      sudo_users:
        - root
        - vagrant
        - "%sudo"
      users_create_per_user_group: false
  tasks:
    - name: Update package lists
      apt: update_cache=yes
    - name: Install common software
      apt: name={{ item }} state=present
      with_items:
        - htop
        - vim
        - sudo
        - zsh
        - screen
    - name: Remove unwanted packages
      apt: pkg={{ item }} state=absent purge=yes
      with_items:
        - dbus
        - tasksel
        - tasksel-data
        - debconf-i18n
        - nfacct
        - xdg-user-dirs
        - nano
        - vim-tiny
    - name: Install available package updates
      apt: upgrade=dist purge=yes

    ##############################
    # Install prezto
    - name: Install zprezto for federico
      git: repo=https://github.com/sorin-ionescu/prezto.git
           dest=/home/federico/.zprezto
           recursive=yes
    - file: dest=/Users/federico/.zprezto/runcoms/zlogin    src=/Users/federico/.zlogin    state=link
    - file: dest=/Users/federico/.zprezto/runcoms/zpreztorc src=/Users/federico/.zpreztorc state=link
    - file: dest=/Users/federico/.zprezto/runcoms/zprofile  src=/Users/federico/.zprofile  state=link
    - file: dest=/Users/federico/.zprezto/runcoms/zshenv    src=/Users/federico/.zshenv    state=link
    - file: dest=/Users/federico/.zprezto/runcoms/zshrc     src=/Users/federico/.zshrc     state=link
    - name: Fix permissions after zprezto install
      command: chown -R federico:federico /Users/federico
    ##############################

    #
    # experimental features
    #
    # - name: Disable overscan
    #  replace: dest=/boot/firmware/config.txt regexp='^#disable_overscan=1' replace='disable_overscan=1'
    # - include: load_balancers.yml
    # - name: Resize root partition to maximum size
    #  command: printf "p\nd\n2\nn\np\n\n\n\nw\n" | fdisk /dev/mmcblk0
    # - name: Resize the file system, too
    #  command: resize2fs /dev/mmcblk0p2