---
- name: apply common configuration to raspberry pi nodes
  hosts: localhost
  remote_user: root
  vars:
    sshd_skip_defaults: true
    sshd:
      Compression: true
      GSSAPIAuthentication: no
      PermitRootLogin: no
    users:
      - username: federico
        name: Federico Castagnini
        groups: ['sudo']
        shell: /usr/bin/zsh
        uid: 2001
        password: 97826a735e4975aa147526ef23f099f0f9efef131f8269e698dfe539c8cf6f95e550224870b7a740773f99dee18b546102234607e8b5be961dfc6f207b540d3a
        ssh_key:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIWzy21UpPuFHiX0ENDB0K7SEFvOQW00REvlITr6MnZEI1izGpfhPh4Bfns/dx8IBf5pQZnJsqR1WdHCg9feqSb9gpyLl1CPnT1mXQJYefelSwgjQA5r8JEwPBLQldQeVYbWmeJbnzU7iJQsA8qQW9/D5ETTMl4fiJ4edrtFTJblHhq3kfJBACvfBEPE78hFSe/GgTe9mvQRMhhwXqhofUZ//oN6wLtXDH4IoLVOPpnMhPHVCL9kaThq8DbNLDkl5ZNIzT2pCKmtavVzJ3XeOnSJUuGKFvLqpqBanRHvt1Glfy3VEzOkCz9GUMF3u+/v+UUtOrESocfSOFy2QWYAbZ fede@arroz-con-leche"
    raspberry_pi_boot_config_options:
        # dont load the audio kernel module
      - regexp: "^#?dtparam=audio"
        line: "dtparam=audio=off"
        # minimize the gpu mem
      - regexp: "^#?gpu_mem"
        line: "gpu_mem=16"
  roles:
    - { role: tersmitten.timezone }   # set timezone to UTC
    - { role: tersmitten.locales }    # set locale to en_US.UTF-8 UTF-8
    - { role: tersmitten.ntp }
    # - { role: tersmitten.swapfile, swapfile_size: 4GB, swapfile_swappiness: 10 }
    - { role: jnv.unattended-upgrades }
    - { role: mattwillsher.sshd }
    - role: tersmitten.fail2ban
      fail2ban_services:
      - name: ssh
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 5
        findtime: 1800
    - role: singleplatform-eng.users
    - role: mivok0.sudo
      sudo_users:
        - root
        - vagrant
        - travis
        - "%sudo"
      users_create_per_user_group: false
    - role: geerlingguy.raspberry-pi
  tasks:
    - name: Update package lists
      apt: update_cache=yes
    - name: Install common software
      apt: name={{ item }} state=present
      with_items:
        - htop
        - vim
        - sudo
        - zsh
        - screen
    - name: Remove unwanted packages
      apt: pkg={{ item }} state=absent purge=yes
      with_items:
        - dbus
        - tasksel
        - tasksel-data
        - debconf-i18n
        - nfacct
        - xdg-user-dirs
        - nano
        - vim-tiny
    - name: Install available package updates
      apt: upgrade=dist purge=yes

    ##############################
    # Install prezto
    - name: Install zprezto for federico
      git: repo=https://github.com/sorin-ionescu/prezto.git
           dest=/home/federico/.zprezto
           recursive=yes
    - name: Fix permissions after zprezto install
      command: chown -R federico:federico /home/federico/.zprezto
    - name: Linking zprezto rc files
      file: src=/home/federico/{{ item.src }} dest=/home/federico/{{ item.dest }} owner=federico group=federico force=no
      with_items:
        - { src: '.zprezto/runcoms/zlogin',    dest: '.zlogin' }
        - { src: '.zprezto/runcoms/zpreztorc', dest: '.zpreztorc' }
        - { src: '.zprezto/runcoms/zprofile',  dest: '.zprofile' }
        - { src: '.zprezto/runcoms/zshenv',    dest: '.zshenv' }
        - { src: '.zprezto/runcoms/zshrc',     dest: '.zshrc' }
    ##############################

    - cron: name="duckdns update sample" minute="*/15" user="federico"
            job="echo url=\"https://www.duckdns.org/update?domains=$(/bin/hostname).duckdns.org&token=exampletoken&ip=\" | curl -k -o /tmp/duck.log -K - >/dev/null 2>&1"
            cron_file=duckdns-update.sample
            state=present
            disabled=yes
    - sysctl:
        name: vm.swappiness
        value: 5
    - sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
    - sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
    - sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
    - sysctl:
        name: net.ipv6.conf.eth0.disable_ipv6
        value: 1
    - name: Enable /tmp tmpfs
      command: systemctl enable tmp.mount
      args:
        creates: /lib/systemd/system/tmp.mount
