# from galaxy

# common
 - src: tersmitten.timezone
 - src: tersmitten.locales
 - src: tersmitten.ntp
 - src: tersmitten.swapfile
 - src: tersmitten.pip
 - src: tersmitten.fail2ban
 - src: jnv.unattended-upgrades
 - src: mivok0.users
 - src: mivok0.sudo
 - src: mivok0.hosts
 - src: 0x46616c6b.sshd
 - src: pbuyle.exim4
 - src: MichaelRigart.aliases
 - src: mikegleasonjr.firewall
