# from galaxy

# common
 - src: tersmitten.timezone
 - src: tersmitten.locales
 - src: tersmitten.ntp
# - src: tersmitten.swapfile
 - src: tersmitten.pip
 - src: tersmitten.fail2ban
 - src: tersmitten.sudoers
 - src: jnv.unattended-upgrades
 - src: singleplatform-eng.users
 - src: mivok0.hosts
 - src: reallyenglish.sshd
 - src: geerlingguy.raspberry-pi
 - src: dev-sec.os-hardening
