# from galaxy

# common
 - src: tersmitten.timezone
 - src: tersmitten.locales
 - src: tersmitten.ntp
# - src: tersmitten.swapfile
 - src: tersmitten.pip
 - src: tersmitten.fail2ban
 - src: jnv.unattended-upgrades
 - src: singleplatform-eng.users
 - src: mivok0.sudo
 - src: mivok0.hosts
 - src: mattwillsher.sshd
# - src: pbuyle.exim4
# - src: MichaelRigart.aliases
# - src: mikegleasonjr.firewall
 - src: geerlingguy.raspberry-pi
