# from galaxy

# common
 - src: oefenweb.timezone
 - src: oefenweb.locales
 - src: oefenweb.ntp
 - src: oefenweb.swapfile
 - src: oefenweb.pip
 - src: oefenweb.fail2ban
 - src: oefenweb.sudoers
 - src: jnv.unattended-upgrades
 - src: singleplatform-eng.users
 - src: mivok0.hosts
 - src: reallyenglish.sshd
 - src: geerlingguy.raspberry-pi
 - src: dev-sec.os-hardening
